6:10 error: x already exists in context
